# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(Version.Major).$(Version.Minor)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BuildAgentIPAddress:

stages:
- stage: Build
  jobs:
  - job: BuildApp
    displayName: Build App
    condition: true
    pool: 
      vmImage: 'windows-latest'
    steps:
      - template: pipeline/build.yml


- stage: DeployDev    
  displayName: Deploy Dev
  variables:
    - group: DEV
  dependsOn: Build
  condition: |
    and (
      succeeded(), 
      ne(variables['Build.Reason'], 'PullRequest') 
    )    
  jobs:
  - deployment: DeployWebApp
    displayName: Deploy Web App
    pool: 
        name: Hosted Windows 2019 with VS2019
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps: 
            - task: AzureKeyVault@1
              displayName: Get KeyVault Secrets
              inputs:
                azureSubscription: RG-APP-DEV-SUB-SC
                KeyVaultName: APP-DEVELOPER-SUB2-KV
                SecretsFilter: '*'

            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: echo '$(Environment.Name)'
                                
            - template: pipeline/deploy.yml
              parameters: 
                environment: $(Environment.Name)
                serviceConnection: RG-APP-DEV-SUB-SC
                allowedAudiences: api://6433b320-58cf-40a4-ab1b-a7ae26b15bce
                clientId: 6433b320-58cf-40a4-ab1b-a7ae26b15bce
                issuerUrl: https://login.microsoftonline.com/37a72eb7-1faf-49d3-9ddc-6b923b751bc0/
                sqlPassword: $(sqldevopsPassword)


- stage: DeployTest
  displayName: Deploy Test
  variables:
    - group: TEST
  dependsOn: DeployDev
  condition: |
    and (
      succeeded(), 
      eq(variables['Build.SourceBranchName'], 'master')
    )    
  jobs:
  - deployment: DeployWebApp   
    displayName: Deploy Web App
    pool: 
        name: Hosted Windows 2019 with VS2019
    environment: TEST
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureKeyVault@1
              displayName: Get KeyVault Secrets 
              inputs:
                azureSubscription: RG-APP-TEST-REF-VDT-SC
                KeyVaultName: APP-TEST-AUA-REF-VDT-KV
                SecretsFilter: '*'

            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: echo '$(Environment.Name)'

            - template: pipeline/deploy.yml
              parameters: 
                environment: $(Environment.Name)
                serviceConnection: RG-APP-TEST-REF-VDT-SC
                allowedAudiences: https://vesseldesign.testapps.alcoa.com
                clientId: 5376fdc0-99d2-4fb8-8ea1-12b60712b0ce
                issuerUrl: https://login.microsoftonline.com/37a72eb7-1faf-49d3-9ddc-6b923b751bc0/
                sqlPassword: $(APP-TEST-AUA-REF-VDT-DB)
             
                
- stage: DeployProd    
  displayName: Deploy Production
  variables:
    - group: PROD
  dependsOn: DeployTest
  condition: |
    and (
      succeeded(), 
      eq(variables['Build.SourceBranchName'], 'master') 
    )    
  jobs:
  - deployment: DeployWebApp
    displayName: Deploy Web App
    pool: 
        name: Hosted Windows 2019 with VS2019
    environment: PROD
    strategy:
      runOnce:
        deploy:
          steps: 
            - task: AzureKeyVault@1
              displayName: Get KeyVault Secrets
              inputs:
                azureSubscription: RG-APP-PROD-REF-VDT-SC
                KeyVaultName: APP-PROD-AUA-REF-VDT-KV
                SecretsFilter: '*'
                
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: echo '$(Environment.Name)'
            - template: pipeline/deploy.yml
              parameters: 
                environment: $(Environment.Name)
                serviceConnection: RG-APP-PROD-REF-VDT-SC
                allowedAudiences: https://vesseldesign.apps.alcoa.com
                clientId: f6fe680d-4e37-4ee6-9aa4-f086ae7f3b2b
                issuerUrl: https://login.microsoftonline.com/37a72eb7-1faf-49d3-9ddc-6b923b751bc0/
                sqlPassword: $(APP-PROD-AUA-REF-VDT-DB)